### ISSUE TITLE
12-STABLE branch creation task list

### ISSUE THREAD

**Issue by lattera** [HardenedBSD/hardenedBSD#353]
- [ ] Create the hardened/stable/12/master branch (@opntr)
- [ ] Update the hbsd-update.conf in the hardened/stable/12/master branch (@lattera)
- [ ] Build new binary update for hardened/stable/12/master users (@lattera)
- [ ] Duplicate the 12-CURRENT package repo for 12-STABLE users (@lattera)
- [ ] Kick off a new package build for 12-STABLE users (@lattera)

**Comment by lattera** [comment]
The hosting provider is performing network maintenance this evening. I plan to kick off a 13-CURRENT/amd64 package build tomorrow. The SoftIron OverDrive 1000, which builds our arm64 packages, is at home. I will kick off a 13-CURRENT/arm64 package build tonight.

**Comment by lattera** [comment]
The amd64 package building server's NICs are dying. I plan to buy and install a new NIC this coming week.

**Comment by lattera** [comment]
New NIC installed yesterday. 13-CURRENT/amd64 package build started yesterday.

**Comment by lattera** [comment]
Note that it will take around one month for the 13-CURRENT/arm64 package build to finish.

**Comment by lattera** [comment]
13-CURRENT/amd64 package build completed and published.

**Comment by pernila** [comment]
With a quick glance (besides the openssl caused breakages) most thing are
working :)

One thing that is causing me issues is secadm.ko

kldload secadm.ko
creates these lines in dmesg:

KLD secadm.ko: depends on kernel - not available or version mismatch
linker_load_file: /boot/modules/secadm.ko - unsupported file type

More info just if needed:
file /boot/modules/secadm.ko shows the it's the normal ELF 64bit binary
with size of 50512

This is issue 354 now in github

https://github.com/HardenedBSD/hardenedBSD/issues/354

**Comment by opntr** [comment]
https://github.com/HardenedBSD/tools/commit/410ea29229acb18120cc33d705e1fa0d7500c4e3
https://github.com/HardenedBSD/tools/commit/2b0517af37e9f8716fd7cf6920cf7ff63a0561e1

**Comment by lattera** [comment]
@opntr are you able to ssh into the Jenkins box? I'm not.

**Comment by lattera** [comment]
Unless @opntr has gotten to it before me, the last thing to do is to update the Jenkins chroot. That should only be done once the Jenkins box itself is updated to 12-STABLE.

**Comment by lattera** [comment]
FYI: There's still more fallout from ifunc in libc. I don't think we should release our first 12-STABLE build from the STABLE repo until the fallout is resolved.
